### PR TITLE
Resolve css/js Media paths using static templatetag

### PR DESCRIPTION
**Pull request by dsanders11**
Same change as stephenmcd/mezzanine#1411

### CODE REVIEW

**Comment by stephenmcd** [comment]
Thanks David

**Comment by stephenmcd** [comment]
More info here: https://github.com/stephenmcd/mezzanine/pull/1411

**Comment by dsanders11** [comment]
@jlirochon, please read the explanation @stephenmcd linked. It is necessary to get the hashed version of file names when using storages like `ManifestStaticFilesStorage`.

Considering I have used that exact setting (`STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'`) for well over a year with this change and many `collectstatic` runs, I do not think this change is the root cause of your crash.

**Comment by jlirochon** [comment]
Thanks @dsanders11 and @stephenmcd,

I'm going to test on a fresh project without other changes, and see if I can reproduce the same problem. I will create another ticket if it makes sense.

**Comment by jlirochon** [comment]
I created issue #317

**Pull request merged**
