### PR TITLE
Main refactor to Django 4.0 and a similar Setup as Mezzanine 5.1

### PR DESCRIPTION
**Pull request by henri-hulski**
Making similar upgrades as in Mezzanine 5.1 which the same modern setup and configuration.
I was going through all the latest history from Mezzanine and made similar changes.
All tests are passing.
I didn't update the docs or Changelog, but I think it can be merged.

This includes also #356 as I started from that branch.

### CODE REVIEW

**Comment by henri-hulski** [comment]
@jerivas Could you take a look please. :)

**Comment by jerivas** [comment]
Hi @henri-hulski 👋 Thanks for your contribution, I can see you put a lot of work into it. Unfortunately I'm currently unable to further maintain this project. I think the best alternative is to migrate Cartridge to [Jazzband](https://jazzband.co/). Would you be interested in taking the main maintainer role over there?

**Comment by henri-hulski** [comment]
Hi @jerivas!
That would be ok.
I can be the maintainer for now.
Hope you will still be able to maintain mezzanine.

**Comment by henri-hulski** [comment]
So how would that work?
Can you do the migration to Jazzband?

**Comment by jerivas** [comment]
> Can you do the migration to Jazzband?

I will have to coordinate that with Stephen (the original author of Cartridge). For now knowing that you can take over should be enough

> Hope you will still be able to maintain mezzanine.

Yep, that's the plan 😊

**Comment by henri-hulski** [comment]
@jerivas Are there any news from Stephen?
Otherwise I'm thinking about forking cartridge to let's say `mezz.shop`.
The `mezz.` namespace could also be used for other Mezzanine plugins e.g. on my side `mezz.braintree`.

**Comment by henri-hulski** [comment]
@jerivas  Any news from Stephen?
Otherwise I'm thinking about forking `cartridge` to let's say `mezz.shop`.
The `mezz.` namespace could also be used for other mezzanine enhancements/plugins.
On my side e.g. `mezz.braintree`.

**Comment by henri-hulski** [comment]
@jerivas What do you think?

**Comment by jerivas** [comment]
I have pinged Stephen, and I would suggest waiting a bit more. Maintaining a new fork with it's own repo and PyPI package is not a small task. You can install directly from GitHub for your own projects if that's urgent.

Just my 2 cents 🙂

**Comment by henri-hulski** [comment]
So I think I will wait to the end of the month.
I've already some experience in maintaining packages. I was quite active in the Morepath community creating and maintaining some plug-ins and even later maintaining the main Morepath Framework.
Als I'm active with Cerebral / Overmind - a JS/TS state and side-effect management.
So I'm quite good in organizing repos and updating dependencies. For cerebral we even created our own tool to manage monorepos (repo-cooker).
But I think I would also prefer to continue with cartridge, so let's wait a bit more. :)

**Comment by stephenmcd** [comment]
Henri, I just added you as a contributor, thank you for this work and for taking the reigns.

**Comment by henri-hulski** [comment]
@stephenmcd
Thanks Stephen!
Would be really a pity to give up Cartridge.
Actually using it for a new project, so I have some ambition to modernize and fix it a bit.
BTW are you ok, if I remove the integrated payment solutions? They seem to be all broken.
I just upgraded cartridge_braintree to Braintree web API v3. Will release it in some days.
I think it's easier to keep the payment to external plug-ins as the external APIs are changing quite fast.

**Pull request merged**
