### PR TITLE
Fix authorize.net for python3

### PR DESCRIPTION
**Pull request by slav0nic**

### CODE REVIEW

**Comment by slav0nic** [comment]
will be fine have better test coverage for payments ;)

**Comment by stephenmcd** [comment]
Does this also work with Python 2.7?

**Comment by slav0nic** [comment]
yes, work

**Comment by stephenmcd** [comment]
Cool, thanks :-)

**Comment by stephenmcd** [comment]
BTW you'll see some tests failed due to pep8 checking - please make sure next time, and thanks again for the fix!

**Comment by slav0nic** [comment]
hm, as run tests?) testrunner didn't work for me (mezzanine4 + git cartridge)

also egate module looks like broken too

**Pull request merged**
