### PR TITLE
Add CHECKOUT_STEP_PAYMENT to checkout view context

### PR DESCRIPTION
**Pull request by dsanders11**

### CODE REVIEW

**Comment by stephenmcd** [comment]
Is this necessary? I think there's some logic already in the templates somewhere that can infer if you're on the payment step.

**Comment by dsanders11** [comment]
Not that I know of, easily. My use case was I need the 'Next' button in `templates/shop/checkout.html` to say something different on the payment step. So while `templates/shop/payment.html` extends `checkout.html`, there's no way to change the form defined in `checkout.html` without duplicating the HTML.

I suppose you could use `step.title` to infer it, but that's fragile. Seemed like a harmless enough extension to the context. It's not like `CHECKOUT_STEP_FIRST` is really necessary either since it's just step == 1.

**Comment by stephenmcd** [comment]
I see, you're right. Might be better if we always just include it as another variable in the context like `CHECKOUT_STEP_FIRST` and `CHECKOUT_STEP_LAST` rather than conditionally. What do you think?

**Comment by dsanders11** [comment]
It could always be in the context, yes, but then there'd probably still need to be an `if settings.SHOP_PAYMENT_STEP_ENABLED` to ensure that it's always accurate to prevent bugs (it is initialized to `CHECKOUT_STEP_FIRST`, so if the payment step was disabled it would incorrectly be true on the first payment step).

Let me know what you'd prefer and I'll make the change.

**Comment by stephenmcd** [comment]
Sure, I guess something like

`"CHECKOUT_STEP_PAYMENT": settings.SHOP_PAYMENT_STEP_ENABLED and step == checkout.CHECKOUT_STEP_PAYMENT,`

**Comment by dsanders11** [comment]
Okay, I've updated the pull request (forced it back to a single commit to keep history clean).

**Comment by stephenmcd** [comment]
Nice one, thanks a lot David.

**Pull request merged**
