### PR TITLE
handle % tax total

### PR DESCRIPTION
**Pull request by meomancer**
hello @stephenmcd 
i made PR that handled % tax
i updated it because i need percentage instead of flat

### CODE REVIEW

**Comment by stephenmcd** [comment]
The intention has always been that tax is calculated as a percentage via the `SHOP_HANDLER_TAX` setting, so I don't think this PR makes much sense.

**Comment by meomancer** [comment]
@stephenmcd 
could you explain me how to make tax calculated in percentage?
i tried changed
def vat_tax_handler(request, order

> _form):
>     """
>     Default tax handler - called immediately after the handler defined
>     by ``SHOP_HANDLER_BILLING_SHIPPING``. Implement your own and
>     specify the path to import it from via the setting
>     ``SHOP_HANDLER_TAX``. This function will typically contain any tax
>     calculation where the tax amount can then be set using the function
>     ``cartridge.shop.utils.set_tax``. The Cart object is also
>     accessible via ``request.cart``
>     """
>     settings.use_editable()
>     set_tax(request, _("Vat"), '14')

it is just add in flat (not in percentage)

**Comment by stephenmcd** [comment]
> @stephenmcd 
> could you explain me how to make tax calculated in percentage?
> i tried changed
> def vat_tax_handler(request, order
> 
> _form):
> """
> Default tax handler - called immediately after the handler defined
> by SHOP_HANDLER_BILLING_SHIPPING. Implement your own and
> specify the path to import it from via the setting
> SHOP_HANDLER_TAX. This function will typically contain any tax
> calculation where the tax amount can then be set using the function
> cartridge.shop.utils.set_tax. The Cart object is also
> accessible via request.cart
> """
> settings.use_editable()
> set_tax(request, _("Vat"), '14')
> 
> it is just add in flat (not in percentage)

`set_tax(request, _("Vat"), request.cart.total_price() / 100 * percentage)`

**Comment by meomancer** [comment]
@stephenmcd thank you very much

**Pull request closed without merging**
