### PR TITLE
Delete order on any Exception from payment_handler, not just CheckoutError

### PR DESCRIPTION
**Pull request by dsanders11**

### CODE REVIEW

**Comment by stephenmcd** [comment]
Don't feel comfortable about this - it'll mask bugs in any of the payment handlers.

**Comment by dsanders11** [comment]
As opposed to users currently seeing an error and having a dangling order. ;-)

Two alternatives:
* Move the if/else block down and if not a CheckoutError then raise the exception again, but at least the order is deleted
* Add a logging statement which would log the exception but then display the user friendly 'Error occurred during payment processing'

Cartridge could benefit from starting to use the logging module, IMO, so I'd favor the second alternative.

**Comment by stephenmcd** [comment]
I'd be more inclined to go with the former since it won't mask the error, but the order data may be useful in reproducing the bug in the code.

I realise you must have been bitten by this in order to address it, but leaving it as is will ensure the payment processors are as bug free as possible.

**Comment by dsanders11** [comment]
Yes, and if you get bitten it tends to bite hard. A transient exception in the payment processor code (gateway connection problem) or an unidentified error case in the API can lead to users creating hundreds of bad orders if the site takes a good amount of traffic.

While the order data could be useful in reproducing the bug, it also is a major pain to clean up the bad order data in the database, especially if it was a transient bug where invalid orders are interspersed with valid ones.

The best practice for keeping the order data for aiding in debugging would be to log it along with the exception.

**Pull request closed without merging**
