### PR TITLE
Fix travis builds

### LINKED ISSUE #335: Travis checks fail with pip --allow-unverified for pyPdf
For Python 3 versions, the Travis build fails with `no such option: --allow-unverified`.

```
no such option: --allow-unverified
The command "pip install . --allow-unverified pyPdf" failed and exited with 2
```

### LINKED ISSUE #336: django.urlresolvers was moved in Django 1.10
`django.core.urlresolvers` was moved to `django.urls` in version 1.10. This is also needed for Django 1.11, which is still supported.

```
  File "/home/travis/build/owenh000/cartridge/cartridge/shop/models.py", line 10, in <module>
    from django.core.urlresolvers import reverse
ImportError: No module named 'django.core.urlresolvers'
```

### LINKED ISSUE #337: Travis is not testing current Django builds
Travis is current checking 1.8, 1.9, and 1.10, none of which are currently support according to <https://www.djangoproject.com/download/#supported-versions>. Travis is not checking the currently supported Django LTS release, which is 1.11.

### PR DESCRIPTION
**Pull request by owenh000**
This pull request contains the necessary fixes to make the Travis builds work again. Please see the commit descriptions. Closes #335, closes #336, and closes #337.

### CODE REVIEW

**Comment by owenh000** [comment]
Feedback is welcome, thanks!

**Comment by jerivas** [comment]
Hi Owen. Thanks for your work on this and the other issues!

Would you want to also contribute fixes to add support for Django 2.0 and 2.1? We want to stay compatible with whatever Django versions are currently supported (as seen in the [official docs](https://www.djangoproject.com/download/#supported-versions)), which currently are 1.11, 2.0, and 2.1.

**Comment by owenh000** [comment]
Hi Ed, thanks for merging the pull requests for the other issues.

I am interested in working on adding support for Django 2.x. However, it will depend on available time and community support. Currently, Cartridge is being tested against Django 1.8, 1.9, and 1.10, none of which are currently supported (see #337). Also, the Travis builds are failing (see #335). This pull request updates to Django 1.11 and fixes the Travis builds. Could you go ahead and merge this pull request, as it is an improvement over the current situation? Additional work on supporting Django 2.0 can come later.

Thanks!

**Comment by jerivas** [comment]
I wanted to see if we could get 2.0 support landed at the same time, but you're right, let's fix one thing at a time. Thanks again!

**Pull request merged**
