### PR TITLE
Mark settings.SHOP_ORDER_EMAIL_SUBJECT as translatable

### PR DESCRIPTION
**Pull request by jpulgarin**

### CODE REVIEW

**Comment by stephenmcd** [comment]
Not sure this makes sense - the default value for the setting is already translatable, see: https://github.com/stephenmcd/cartridge/blob/master/cartridge/shop/defaults.py#L234

**Comment by jpulgarin** [comment]
This is for the case where the value is overridden in `settings.py` since `ugettext` cannot be imported there.

**Comment by stephenmcd** [comment]
According to the Django docs you can use ugettext_lazy in setting.py

**Comment by jpulgarin** [comment]
Oh neat. I was going by the Django 1.4 docs (https://docs.djangoproject.com/en/1.4/topics/i18n/translation/#how-django-discovers-language-preference) which mention an awkward workaround. I think they must've made a mistake in the docs since ugettext_lazy importing in settings.py works in Django 1.4, and the new docs have since moved to this method.

**Comment by stephenmcd** [comment]
Yeah, those docs actually show a trick for using translations in settings modules back then, something like:

ugettext = lambda s: s

Thanks all the same.

**Pull request closed without merging**
